### PR TITLE
[4.0] Possibility to specify a branch to a server

### PR DESCRIPTION
**Pull request by InfinityWebMe**
Hello,

this commit add the possibility to specify a branch to a server.

Example : production = master AND staging = develop

Any comments or improvements are welcome :)

### CODE REVIEW

**Comment by banago** [comment]
Looks great again. One question - why the change from:

    exec(escapeshellcmd($command), $output);

To:  

    $output = null;
    exec("({$command}) 2>&1", $output);

Just asking - I don't know the difference.

**Comment by InfinityWebMe** [comment]
Hello, thanks :-)

2>&1 force stderr to output var. I forget to put  escapeshellcmd. Il assure thé commit tomorow :-)

**Comment by banago** [comment]
Awesome. Please add the escape and I'll merge right away. Thank you very much for your contributions.

**Comment by InfinityWebMe** [comment]
It's done ;-)

**Comment by banago** [comment]
:100:

**Pull request merged**
