### PR TITLE
Remove leftover debug code?

### PR DESCRIPTION
**Pull request by JayBizzle**
Was this supposed to be here?

### CODE REVIEW

**Comment by banago** [comment]
No, actually. :) But why can't I merge automatically?

**Comment by JayBizzle** [comment]
Probably conflicting with the other PR from me you just merged.

**Comment by banago** [comment]
Yep, that was it. Merged it through command line.

**Comment by JayBizzle** [comment]
Beat me to it :+1:

**Comment by banago** [comment]
Thanks for pointing it out. That was awesome!

**Pull request merged**
