### PR TITLE
Return 1 on error so they can be detected in automated environments

### PR DESCRIPTION
**Pull request by mbrugger**
I use PHPloy in a jenkins job and this little change should help to detect errors when executing PHPloy

### CODE REVIEW

**Comment by banago** [comment]
Happy to add this, thanks @mbrugger. Can you tell me in a few words how Jenkins makes use of this?

**Comment by mbrugger** [comment]
If a script returns a non zero value the jenkins job will fail and not continue deployment.
Maybe have a look at this [article](http://bencane.com/2014/09/02/understanding-exit-codes-and-how-to-use-them-in-bash-scripts/) which describes the usage of exit codes very well

**Comment by banago** [comment]
Don't you want the deployment to stop if a issue happens in PHPloy?

**Comment by mbrugger** [comment]
Exactly, PHPloy so far returned 0 on error which indicated success. Therefore the change to return 1 which means error.

**Comment by banago** [comment]
Right. Let's do it.

**Comment by mbrugger** [comment]
done

**Pull request merged**
