### PR TITLE
Allow to configure patterns that a file must match to be uploaded.

### PR DESCRIPTION
**Pull request by martin-sucha**

### CODE REVIEW

**Comment by banago** [comment]
@martin-sucha Thanks for the contribution. What would be an use-case for this? Also, can you please update readme.md file accordingly about this change.

**Comment by martin-sucha** [comment]
@banago I've updated the readme.

I only want to deploy two subdirectories inside my repository that correspond to two subdirectories in my SFTP account. I don't want to list all other files in my repo (e.g. docs, dev scripts, etc.) in `skip[]` manually.

**Comment by banago** [comment]
@martin-sucha so this is the reverse of `skip`, right? Will this include directories that are normally ignored by Git such as `vendor`? Or this will work only with the Git tree?

**Comment by martin-sucha** [comment]
Not sure I'd call it a reverse of `skip`, it is more a `skip` with negative pattern match, since it does not add any files to the list of the files to be transferred, only allows you to ignore any files not matching any of the patterns.

It filters the same list of files that is passed for filtering with `skip`, so the rules for non-git files should be the same as for `skip`, i.e. it depends on whether you used the `-o` option or not.

Hmm, so we may also rename `include` to `skipNot` or something else if you can think of a better name.

**Comment by martin-sucha** [comment]
@banago does my previous comment answer your question?

**Comment by banago** [comment]
I'm on vacation - will get to you as soon as I can. Thanks very much.

**Comment by banago** [comment]
@martin-sucha so I still need a little feedback on this. Will this ignore everything expect what you add to `include[]` or this will just unskip any files previously skipped by `skip[]`?

**Comment by martin-sucha** [comment]
@banago it will ignore everything except what you add to `include[]`

**Comment by martin-sucha** [comment]
@banago any news on this PR? Thanks.

**Comment by banago** [comment]
Hey @martin-sucha, sorry, I've been very busy. I'd be happy to merge this right away at this point, but I cannot merge it strait from Github any more. I can you please pull latest `master` and update the pull request. Thanks very much.

**Comment by martin-sucha** [comment]
@banago I've updated the branch and also fixed a small bug I noticed during merging.

And I've just noticed that when merging I accidentally commited also a regenerated phar, should I rebase the branch to remove this change? Or generate a new phar that includes the more recent commits (since those aren't included yet)? Or will you do it? Hmm, this should be probably written down somewhere, I'm opening a separate issue for that, see #142.

**Comment by banago** [comment]
@martin-sucha that's funny. :smile: 

Don't worry about old commits. Please produce a new build for latest commit and push it up. I merge this through Github when commits are alright. Waiting for your update.

**Comment by martin-sucha** [comment]
@banago I've pushed the build. Thanks.

**Comment by banago** [comment]
@martin-sucha thanks very much - great work!

**Pull request merged**
