### PR TITLE
Copy phploy.phar into project's bin directory

### PR DESCRIPTION
**Pull request by bigfoot90**
Copy ```phploy.phar``` into project's ```bin``` directory

### CODE REVIEW

**Comment by banago** [comment]
@bigfoot90 we have an option issue for this here: #152 

I'm sorry that I won't be able to merge your pull request because it's not how it should be done. If you want to take over issue #152 and follow Composer's docs, that would be awesome.

**Comment by bigfoot90** [comment]
I alredy have in my ```composer.json``` this config, but the directory has not been created.
```json
{
    "config": {
        "bin-dir": "bin"
    }
}
```

As you can see [here](https://getcomposer.org/doc/articles/vendor-binaries.md#what-happens-when-composer-is-run-on-a-composer-json-that-has-dependencies-with-vendor-binaries-listed-) you have to tell to composer wich files copy to the ```bin``` directory.

**Comment by banago** [comment]
Yes, but the docs say a CLI interface should be in the bin, not the
archive.

**Comment by bigfoot90** [comment]
Prease read the official composer's doc https://getcomposer.org/doc/articles/vendor-binaries.md#what-is-a-vendor-binary-

> Any command line script that a Composer package would like to pass along to a user who installs the package should be listed as a vendor binary.

```phploy.phar``` is a command line tool.

> If a package contains other scripts that are not needed by the package users (like build or compile scripts) that code should not be listed as a vendor binary.

```phploy.phar``` is NOT a build or compile script.

So I didn't see why this cannot be merged.

**Comment by banago** [comment]
Seems you are right and I've misread the documentation, or they have
changed it.

I'll get back to you soon. Thanks.

**Comment by banago** [comment]
@bigfoot90 check how composer handles the bin file. It's basically a little PHP file that calls the app rather then include the `phar` file there.

https://github.com/composer/composer/blob/master/bin/composer

I suggest we do the same at PHPloy too.

**Comment by bigfoot90** [comment]
Sorry, but I don't understand what is the goal of your last post.

Do you want to create a *launcher* for phploy.phar? Why?
Phploy.phar is already an executable file, it doesn't need for a launcher.

Is the a reason why don't like to link the ```phploy.php``` command line into the project ```bin```?

**Comment by banago** [comment]
@bigfoot90 what I'm trying to say is I don't want to include the `phar` file on the repo in the future. It should be served from elsewhere and in the `bin` we can put a file similar to this that can run through `composer`.

**Comment by bigfoot90** [comment]
What is the advantage of doing this?

You can refactor this in a second step.
Why not link phploy.phar temporarily, so the package will be usable by other users who install it via composer?

**Comment by bryanjhv** [comment]
Because Composer asks for a PHP script as binary, not a Phar.

**Pull request closed without merging**
