### PR TITLE
Add option to purge before deploy

### PR DESCRIPTION
**Pull request by Liingon**
Solves #364

### CODE REVIEW

**Comment by freddyroberts** [comment]
@Liingon Great idea. I could use this option for what I'm currently working on. Any idea when you'll be able to merge it in?

**Comment by banago** [comment]
@Liingon thanks for this.

**Comment by Liingon** [comment]
@banago Glad to be able to help. Would be great if you could bump the version number so composer gets the updated files.

**Comment by banago** [comment]
I'll do so this weekend. Thanks again.

**Pull request merged**
