### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Euphorbium**
Fixes issue #26. You can set your username and password as system environment variable.

### CODE REVIEW

**Comment by banago** [comment]
Thanks @Euphorbium,

Did you test this and confirm it's safe to merge?

**Comment by Euphorbium** [comment]
Yes, it is working, but the installation instructions probably could be more clear on HOW to set the system environment variable.  For example in linux you usually set them  in .bashrc file and on windows they are edited in the same place where you edit system path variable.

**Comment by banago** [comment]
Yeah, that would be great. One thing that needs to be update too is to
leave an example with default setup and then add an example with system
variables. Most users don't use system variables, do it's not good to
confuse them. Once you send me an update for that, I will merge it right
away. Thanks very much for your contribution.

**Comment by Euphorbium** [comment]
Now it should be more clear. Made the use of environment variables optional suggestion, and somewhat explained how to set them.

**Comment by banago** [comment]
Thanks very much @Euphorbium and sorry for the late merge! If you want to do further work, please pick any ticket you like and push them through. Your contribution is more then welcome again.

**Comment by eleazan** [comment]
@banago you have lost these merge on v3!

**Comment by banago** [comment]
Yes, unfortunately. Thanks for letting me know. What would be the best approach at this point @eleazan and @Euphorbium?

**Pull request merged**
