### PR TITLE
[4.0] Possibility to execute "local" command after sync

### PR DESCRIPTION
**Pull request by InfinityWebMe**
Hello,

this commit add the possibility to execute commands ( on machine who execute phploy ) after the synchronisation.

In my case, the command execute a wget silently who call a script on my server to execute a composer update.

I fixed too a issue when informations pass and privkey is empty.

Any comments or improvements are welcome :)

### CODE REVIEW

**Comment by banago** [comment]
This seems great. Thanks so much. I have a problem with the naming of the feature though. It's kind of hard to wrap the head around something named `post-local-command`. Could we rename this to something better, especially something that would be more git-like, like `post-deploy` for example?

**Comment by InfinityWebMe** [comment]
hello,

thanks to the feedback.

"post-local-deploy" could be ok for you 'cause it's a local command and not remote.

Do you think is a good idea to get free the name "post-deploy" for remote command.

Sorry for my poor english :)

**Comment by banago** [comment]
No worries about your English - all is clear. 

I'm more about using `post-deploy` and `pre-deploy`. If we add remote commands later, we can extend those to become `post-deploy[remote]` and `pre-deploy[remote]`. So, can you rename those to `post-deploy` please.

**Comment by InfinityWebMe** [comment]
Hello,

it's done. 

I added the possibility to execute commands before the synchronisation.

**Comment by banago** [comment]
Had a look -- looks perfect. Thanks very much @InfinityWebMe

**Comment by ogrosko** [comment]
Can you provide your composer update script
I'm trying to implement some remote update script like [here](https://github.com/composer/composer/issues/1906#issuecomment-51632453) but with no success

**Comment by InfinityWebMe** [comment]
```php
define('_ROOT_DIR', dirname(__FILE__) . '/');

$composer_home = _ROOT_DIR . '/composer/';

function runCommand($bin, $command = '', $force = true)
{
    $stream = null;
    $bin .= $force ? ' 2>&1' : '';

    $descriptorSpec = array
        (
        0 => array('pipe', 'r'),
        1 => array('pipe', 'w')
    );

    $process = proc_open($bin, $descriptorSpec, $pipes);

    if (is_resource($process)) {
        fwrite($pipes[0], $command);
        fclose($pipes[0]);

        $stream = stream_get_contents($pipes[1]);
        fclose($pipes[1]);

        proc_close($process);
    }

    return $stream;
}

runCommand(escapeshellcmd('COMPOSER_HOME="' . $composer_home . '" composer update -v'), '', TRUE);
```

**Comment by ogrosko** [comment]
Great thank you
One last question is it possible to see output of post-deploy?

**Comment by InfinityWebMe** [comment]
```php
echo runCommand(escapeshellcmd('COMPOSER_HOME="' . $composer_home . '" composer update -v'), '', TRUE);
```

**Comment by InfinityWebMe** [comment]
I think, use echo in php script and remove --quiet in wget command

**Comment by ogrosko** [comment]
Hmm I tried this but with no effect

**Comment by InfinityWebMe** [comment]
I create a pull request : https://github.com/banago/PHPloy/pull/242

**Pull request merged**
