### PR TITLE
Store password in a separate file outside of the ini file.

### PR DESCRIPTION
**Pull request by Schnoop**
Store the password outside of the phploy.ini file.
Great feature if you would like to share your phploy.ini file.
It is also usefull for security reasons.

### CODE REVIEW

**Comment by Schnoop** [comment]
Fixed some DocBlocks.

**Comment by banago** [comment]
@Schnoop this is a great feature indeed, thank you for taking the time to implement it. However, it's a but unintuitive and hard to remember. Can you please re-implement this to make use of an argument instead. For example:

    phploy --password="pass-goes-here"

I find this solution much more clean and easy. Let me know.

**Comment by Schnoop** [comment]
I see your point. But in my/our case, we have a team of 5 developers that are working on a project. Not every developer has the permission to deploy to the servers. Nevertheless we would like to share the phploy.ini file to all developers via git, so that modification is possible even by those who will not execute the deployment. To fit our requirement, we have to remove the password from the ini file.

The problem with an argument is, that i have to remember or copy the password from wherever. This is complicated and i don't want to do this all the time over and over again.

Another problem is, that the password will be stored in the bash history, so it's not really save. If the deployment process is running, everybody could grab those infos via "ps -faux".

**Comment by banago** [comment]
I see your point and it makes total sense. And I'd love to accommodate your contribution, but I don't find it clean enough. What do you think of just a `.phploy` config file, instead of a whole directory?

**Comment by Schnoop** [comment]
Yes, i thought about that,but  how to handle multiple passwords, for different servers, in one file? Maybe choose ini as file format? That would be possible, but a bit overhead. 
Am 05.04.2016 12:51 schrieb Baki Goxhaj <notifications@github.com>:I see your point and it makes total sense. And I'd love to accommodate your contribution, but I don't find it clean enough. What do you think of just a .phploy config file, instead of a whole directory?

**Comment by banago** [comment]
Yes, I was thinking of making the `.phploy` in 'ini' format. We can later extend on it and is a start it can be like this:

```ini
[staging]
    password="pass-goes-here"
[production]
    password="pass-goes-here"
```
This might require a bit of more effort to implement, but it's worth it for the user experience. What do you think?

**Comment by Schnoop** [comment]
Allright. Let's do this. I'm out of office for the rest of the day. I'll have a look in the evening or at latest tomorrow.

**Comment by banago** [comment]
Awesome! Take your time, np.

**Comment by banago** [comment]
Pull from master when you restart, I made a small update.

**Comment by Schnoop** [comment]
Ready, set, go! :)

**Comment by banago** [comment]
@Schnoop looks pretty good, thanks a lot. Two things:

Does it work if we remove `.ini` extension from `.phploy.ini`?

Why have you used an `Exception` here:

    try {
        $values = $this->parseIniFile($this->getPasswordFile());
        if (isset($values[$servername]['password']) === true) {
            return $values[$servername]['password'];
        }

        return '';
    } catch (\Exception $e) {
        return '';
    }

It could just be this:

    $values = $this->parseIniFile($this->getPasswordFile());
    if (isset($values[$servername]['password']) === true) {
        return $values[$servername]['password'];
    }
    return;

**Comment by Schnoop** [comment]
I've removed the file suffix. Worked.
Also removed the try - catch block.

**Comment by banago** [comment]
All seems perfect. Thank you for this contribution. :+1:

**Pull request merged**
