### PR TITLE
Hotfix/others fix

### PR DESCRIPTION
**Pull request by andresnijder**

### CODE REVIEW

**Comment by andresnijder** [comment]
this should fix issue #165 & #156

**Comment by banago** [comment]
Thanks @andresnijder :+1:

**Comment by louislam** [comment]
Hi, the hotfix is not in the last commit. I still get the error of "Oh Snap: Unsupported git-diff status: ." in the last version (5.3.6) on Windows.

The hotfix probably overrided by this commit:
https://github.com/banago/PHPloy/commit/abb02f2d6411758acab8ee0b79e62358249754d1

Please check that, thank you.

**Comment by louislam** [comment]
I have made a pull request, please check that.

**Pull request merged**
