### PR TITLE
add ftp-ssl and file permission settings

### PR DESCRIPTION
**Pull request by fsalomon**
see README.md

### CODE REVIEW

**Comment by banago** [comment]
@fsalomon thanks very much for this - great work. Question: where are these values used:

    'permPublic' => 0774,
    'permPrivate' => 0700,

Seems they are not taking effect anywhere.

**Comment by fsalomon** [comment]
Hi! 

Sure, permPublic/permPrivate are used in Banago\PHPloy\Connection where they are passed to the adapters. How they are used is up to the adapters. As far as I understand, if visibility=private, then permPrivate will be used and if visibility=public, then permPublic will be used. Defining both might only make sense for downloading files from an FTP. What I (successfully) archived with this is that all uploaded files and folders are group writable (visibility=public,permPublic=0770). The default setting is pulled from League\Flysystem\Adapter\AbstractFtpAdapter, so this feature is backwards compatible.

It might make sense to merge permPublic, permPrivate and visibility settings into one setting "permissions".

**Comment by banago** [comment]
Yeah, it's very tedious to use like that. We need an simple interface, like `permissions` for this. Would you be able to make this change?

**Comment by fsalomon** [comment]
True, I added the "permission" key and changed the readme. It's still possible to use the low level config values. It's basically a shortcut.

I have done some testing and it definitely works for file permissions. Folders always end up as 0750 regardless of the setting. But that might just be server-side config in my case. Unfortunately, I have no other FTP server to test because... FTP stinks :-)

**Comment by banago** [comment]
@fsalomon thanks very much for your contribution. :+1:

**Pull request merged**
