### PR TITLE
.ini file shouldn't  be indented

### PR DESCRIPTION
**Pull request by decanus**

### CODE REVIEW

**Comment by decanus** [comment]
@banago

**Comment by banago** [comment]
@decanus why is this the case? I wasn't aware of this.

**Comment by decanus** [comment]
My ide seems to be printing an error whenever it is indented. Maybe it is an error on the ide's side (phpstorm) but I would look into it. Not sure if the php ini parser removes whitespace

**Comment by banago** [comment]
It's great they you have PHPloy integrated in PHPStorm. But still phploy
should be reading the `ini` file and not the IDE. What's your actual setup?

**Comment by decanus** [comment]
The error comes when editing the ini file

**Comment by banago** [comment]
OK, let's do it then.

**Pull request merged**
