### PR TITLE
Adding an init parameter to set up sample deploy.ini file

### PR DESCRIPTION
**Pull request by baoweber**
I have added a parameter `--init` that, if given, copies the sample.ini from the root of the document and copies it into the working directory as `deploy.ini`. I will be happy to update that in case I am doing something wrong.

I have tried to keep the process as simple as possible.

### CODE REVIEW

**Comment by baoweber** [comment]
Sorry, I have not added my changes to the phar archive, I will do that and repush into the branch. My bad, did not read the instructions properly, sorry about that.

**Comment by baoweber** [comment]
The phar archive should work now as well, but I had to move teh sample.ini file into the src directory (as I did not want to intervene into the build file).

**Comment by banago** [comment]
@baoweber thanks a lot for this. Can you please update the `readme.md` to reflect this change. Thanks again.

**Comment by baoweber** [comment]
Sure I will do that.

**Comment by baoweber** [comment]
Updated the setup process. Please let me know if you eant me to update anythink else. Thanks a lot!

**Comment by banago** [comment]
@baoweber do you think this is ready for public use? If you confirm, I will merge immediately, but I don't want us to end up with broken features. Let me know.

**Comment by baoweber** [comment]
It should be fine. I tested it in several ways and the changes should not affect any other part of the app. The only parts that I suspect you might want to do differently is the message that the sample file was created (I did not put any colors or such) and also I created just a very simple deploy.ini with basic setup. So if you think I should update those, please let me know.

**Comment by banago** [comment]
Great, thanks. Pulling this in.

**Pull request merged**
