### PR TITLE
Added missing pre/post-deploy-remote hooks

### PR DESCRIPTION
**Pull request by mikaelz**
I discovered pre/post-deploy-remote hooks for SFTP scheme in the code. Should be mentioned.

### CODE REVIEW

**Comment by banago** [comment]
Nice. Are `raname` and `put` real Linux commands?

**Comment by mikaelz** [comment]
Oh, sorry, thought they should be SFTP commands, that's why it didn't work for me :(
Check the code and realised it's executes on SSH2 connection via https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SSH2.php#L2386
I changed the commands for Linux OS

**Comment by banago** [comment]
Perfect. Thanks for all the great contributions. If you find anything else you can address in the list of current issues, I'd be very happy to merge your work. Thanks a lot.

**Comment by mikaelz** [comment]
Thanks for the tool ;)

**Pull request merged**
