### PR TITLE
Added another way to use PHPloy globally on Linux

### PR DESCRIPTION
**Pull request by peterbrinck**

### CODE REVIEW

**Comment by banago** [comment]
@peterbrinck thanks for this. Would this not require to move the PHP archive into the `usr/local/bin`? If yes, can you please explain this and update your pull request?

**Comment by peterbrinck** [comment]
When I wrote it, I tried it out..
But just yesterday I reinstalled Ubuntu on my computer, and now it doesn't seem to work for me.. 

So I'll think of another and easier way

**Comment by peterbrinck** [comment]
Okay, so now it should be correct, and doable with a symlink!

**Comment by banago** [comment]
Makes sense. Thanks for update it so quickly.

**Comment by peterbrinck** [comment]
:+1: 

Thanks for making PHPloy in the first place!!

**Pull request merged**
